### ISSUE TITLE
[UI] Form submission - data sanitization

### ISSUE THREAD

**Issue by jcleefw** [jcleefw/service-calculator-app#10]
## Task
- [ ] should get all data info from form
- [ ] basic validation required
- [ ] data needs to be sanitised for POST request
